name: CI
env:
  TZ: Asia/Shanghai
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '30 16 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.3
    - uses: actions/setup-node@v3.6.0
      with:
        node-version: '20.3.1'
        cache: 'npm'
        cache-dependency-path: package-lock.json
    - name: npm
      run: |
        npm i -g hexo-cli
        npm i
    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3.3.1
      env:
        cache-name: cache-node-modules
      with:
        path: |
          ~/node_modules
          ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: hexo
      run: |
        hexo g --slient
    - name: Deploy
      uses: bluekrow/hexo-auto-deploy@v1.1.0
      with:
        token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        repo_name: penndu/my-website
        owner_name: TeacherDu
        owner_email: penndu@outlook.com
        commit_message: a
        deploy_branch: master
        deploy_dir: /
        source_dir: ./public
    - name: algolia
      run: hexo algolia
